version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-type: "direct"
        update-types: ["version-update:semver-major"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-major"]
