version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: "bump"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
