version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)
    labels: [dependencies, javascript]
    versioning-strategy: increase
    open-pull-requests-limit: 6
