name: Linter

on:
  pull_request:
    branches:
      - master
      - forbidden

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  eslint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run ESLint with fix
        run: npm run lint:fix
      - name: Commit and push changes back to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Irfan Shadik Rishad'
          git config --global user.email '77362427+irfanshadikrishad@users.noreply.github.com'
          git add .
          git diff --quiet || git commit -m "chore: apply linting fixes"
          git push origin HEAD:${{ github.head_ref }}
      - name: Run EsLint without fix
        run: npm run lint
